[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# 编译器设置 - 解决Stack too deep错误
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

# Remappings for dependencies
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
